import { Forum } from '../../assets/js/forum.js';
import { Post } from '../../assets/js/post.js';

const posts = [
  new Post("583", "06/23/02 5:18 PM", `Hey, I need some advise about powers - does anyone here have them? I need some advice. Just got them at school, but things went bad and I'm worried people will be able to trace what happened to me.`),
  new Post("xmx", "06/23/02 5:23 PM", `Heyyy! What's your name?? Do you it picked out already?`),
  new Post("bfg", "06/23/02 5:23 PM", `No way!!! How did you get yours??! Maybe I can do the same thing 🥺`),
  new Post("583", "06/23/02 5:24 PM", `I can't go into details, or share my name. I'm asking for advice on how to be anonymous.`),
  new Post("xmx", "06/23/02 5:24 PM", `I meant your hero name, not your real one! Unless you're thinking of being a villain, haha`),
  new Post("bfg", "06/23/02 5:25 PM", `We can't help unless you give us a little bit of info... Like, what happened?
We can't really tell you how to hide your powers unless you give us a bit more.
And pls give tips on how to get our own powers <3`),
  new Post("583", "06/23/02 5:37 PM", `Ha, thinking about hero.... I'm not sure about a name though. Call me S, I guess. I'll share what I can.
Basically it all happened in chemistry class this morning, because we had this really tough assignment. It was this big test where we had to figure out all the stuff that was mixed into this green liquid the teacher gave us. I've been really stressed about it, because the teacher is really mean and strict - like, he was yelling at this guy in class for using a microscope wrong, and called him an idiot in front of the whole class. So my nerves were pretty shot from the get-go.

I was working with this really tall, handsome guy I know, but we both got sort of stuck at this one point - like, I don't know what the teacher wanted from us, you know?? We tried fractal distillation, spectroscopy, and some other ones the guy knew about better than I did, but it wasn't working. It was really stressful because normally I'm a good student, but I was looking like a total moron in front of him. I think he was a bit disappointed in me, and he was getting more and more frustrated when every test we tried didn't help. He tells me to try doing a freezing point test on some. Pretty simple, right? Put the solution in a beaker, put some salted ice in a dish around it, measure the temperature. A blindfolded chimpanzee could do it, but *apparently* I'm a fucking idiot. It's just that we were nearly out of time, my hands were shaking so bad. I couldn't think straight. I'd just put the ice in, when I realized that I hadn't grabbed the salt. I picked up the tray with the beaker, and turned to run to the table with the salt, but there was someone right behind me. Our teacher does this thing where he stands in the middle of the lab and just glares at people. It always makes me feel like I'm doing something wrong, even if I'm not. Well, guess where he decided to stand? Right. Fucking. Behind. Me. So when I turned, the tray smashed into his arm, and the green liquid and ice just flew everwhere, and all over him. Whatever was in it must've been dangerous, because his eyes *bulged*, before he starts ripping off his shirt. In the meantime, with his sweater-vest half over his head, he starts flipping out and cursing the shit outta me in front of everyone, who are all just staring at me and him. I'm pretty sure I was already crying at this point, and I saw my lab parter looking at me in absolute horror. I was so ashamed, and I felt as heat permeated through my face. It felt like my tears were about to boil as then ran down my cheeks. I remember wishing that I couldn't see anyone, and that they would stop looking at me. When I thought that, it felt like a string was tugging hard at my heart - it stopped my breath. But it was distracting from, you know, EVERYTHING. The people staring, my increasingly-bare-skinned 60 year old teacher, the anger in Tom's eyes. So I kept wishing harder. 

And after a moment, I felt a release - emotional, physical, all of it. I took a deep breath, and it felt like breathing next to a misty waterfall, calm and pleasantly damp. When I opened my eyes, I thought I was blind for a moment. Everything was grayish white, like the thickest fog you've ever seen. I had to blink a lot, since droplets kept pooling on my eyelashes. I put out my hand, playing with the swirling eddys of the gas, and the smoke clung to it like twirling spagetti around a fork. I snapped out of whatever trance I was in when the fire alarm started blaring, and someone opened the door. I could see the sunlight a bit through the fog, enough to locate the door, and we all moved onto the field. Luckily all the classes had doors close together, so everyone mixed pretty quickly. I just found my friends and they told me that their room had filled with some sort of smoke, too. Pretty lucky, I guess. I didn't tell them about what happened in my class, but a few of the mean girls in that class saw me and started pointing a laughing at once point, so I'm sure everyone will know by tomorrow. I didn't see my teacher at all after that. Some of the people outside seemed pretty scared, though. I guess they thought it was some sort of villain attack, or a gas leak or something. The principal ended up making a speach after everyone had made it to the field, and we were told to go home. 

So that's pretty much it - Dad called and said he'd gotten an email to pick me up and my sister up, and that everything was fine but school was canceled. Luckily he didn't ask too many questions, but my sister just kept saying how sure she was that this was because of a villain, and that the smoke could've been poisoned. Dad said if that had been true we would already be 6 feet under, and not to worry. I wasn't really listening. I think he thought I was in shock - told me to relax and play some games. I guess I sort of was, but not because I was stressed. I just felt weird, like I'd just woken up from a very odd dream. I haven't told anyone. 

What should I do now?? Will they figure out it was me? How can I hide it? How do I control this? I'm too scared to try again, but I know it was me. Should I be? I don't know what comes next - should I be testing out my power??`),
  new Post("tg1", "06/23/02 5:39 PM", `Definitely fake, lol. Like that could give someone powers.
You are all are getting baited.`),
  new Post("bfg", "06/23/02 5:40 PM", `So you were just stressed about school? That happens to me all the time, and I still don't have a power
This isn't fairrrr 😭`),
  new Post(`xmx`, "06/23/02 5:40 PM", `No way, S!! That sounds awful - at least your power is super cool!!
Can I be your sidekick?? You should PM me with your main account - I can keep your secret!`),
  new Post("sus", "06/23/02 5:43 PM", `I hate to be that girl, but I'm not so sure about following the whole 'superhero' route.... 
Imagine going up against BubbleBomb, or trying to stop a bank robbery, lol. Best you could hope for is getting out in one piece, with a power like that.. Probably best to play it safe, NGL. There are better powers for heroes out there.`),
  new Post("583", "06/23/02 5:44 PM", `Yea, I guess you're probably right... Does anyone know how I can avoid getting IDd though?? I'm really worried that one of the guys knows it was me, he was staring right at me before the cloud appeared. Is there anyone here with powers who can advise?? Please guys`),
  new Post("tg1", "06/23/02 5:46 PM", `Wow, really laying it on thick LOL
If you're going to make up stories, at least pick a cooler power next time. Give us something interesting to read...`),
  new Post("nav", "06/23/02 5:46 PM", `If this is legit -
Firstly, going to message boards about this stuff is NOT a good idea, lol. People can trace even the guest accounts. But since you already have i'll say this - keeping your identity safe is mega important for ANY [PP]. Villains will go after kids as young as middle school to try to recruit, so you shouldn't reveal your identity to ANYONE, just in case it gets out. 
Def don't skip school, or you'll look super sus. Just act like normal tomorrow, and it'll be fine. If you feel like anyone suspects you, just play dumb. They have no proof, unless you forgot to mention something obvious (like, the smoke didn't come out of you, right??)
Don't ever use in any public area.
Good luck man`),
  new Post("hsw", "06/23/02 5:46 PM", `What if they're just trying to bait a PP into talking to them? Would be pretty genius TBH. Well played if so 👏`),
  new Post("hwk", "06/23/02 5:48 PM", `Wait, that sounds my old chemistry teacher, at South Emmerson High right? That assignment sucked, my condolences girl XD
Wish I coulda dropped a smoke bomb to get outta it too LOL`),
  new Post("583", "06/23/02 5:49 PM", "<i>This thread has been locked</i>")
];

export const forum = new Forum("Power Advice", posts, true);